#!/usr/bin/python3
# library to get arguments
import sys


# function unpack number factorial
def frc():
    """
    function fc to search file to convert number and format n=p*q
    """
    try:
        revf = sys.argv[1]
        with open(revf) as f:
            for revber in f:
                revber = int(revber)
                if revber % 2 == 0:
                        print("{}={}*{}".format(revber, revber // 2, 2))
                        continue
                u = 3
                while u < revber // 2:
                    if revber % u == 0:
                        print("{}={}*{}".format(revber, revber // u, u))
                        break
                    u = u + 2
                if u == (revber // 2) + 1:
                    print("{}={}*{}".format(revber, revber, 1))
    except (IndexError):
        pass


# autostart
frc()
